# Generated by Django 5.1.5 on 2025-01-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='unit',
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='services_images/'),
        ),
    ]
