# Generated by Django 5.1.5 on 2025-01-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardapp', '0003_servicerequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='date',
            new_name='preferred_date',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='time',
            new_name='preferred_time',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
