# Generated by Django 5.1.5 on 2025-01-23 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardapp', '0004_rename_date_servicerequest_preferred_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='preferred_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='preferred_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
