# Generated by Django 5.1.5 on 2025-01-27 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yardapp', '0007_servicerequest_status_remove_servicerequest_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='time',
        ),
    ]
